/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedAssignedAuditsRouteImport } from './routes/_authenticated/assigned-audits'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedMyAuditsRouteImport } from './routes/_authenticated/my-audits'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedAdminAuditsRouteImport } from './routes/_authenticated/admin/audits'
import { Route as AuthenticatedAdminChallengesRouteImport } from './routes/_authenticated/admin/challenges'
import { Route as AuthenticatedAdminCoachAssignmentRouteImport } from './routes/_authenticated/admin/coach-assignment'
import { Route as AuthenticatedAdminCoachesRouteImport } from './routes/_authenticated/admin/coaches'
import { Route as AuthenticatedAdminExpertsRouteImport } from './routes/_authenticated/admin/experts'
import { Route as AuthenticatedAdminReportsRouteImport } from './routes/_authenticated/admin/reports'
import { Route as AuthenticatedAdminRolesRouteImport } from './routes/_authenticated/admin/roles'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as ApiPublicBootstrapDemoRouteImport } from './routes/api/public/bootstrap-demo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAssignedAuditsRoute =
  AuthenticatedAssignedAuditsRouteImport.update({
    id: '/assigned-audits',
    path: '/assigned-audits',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMyAuditsRoute = AuthenticatedMyAuditsRouteImport.update({
  id: '/my-audits',
  path: '/my-audits',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminAuditsRoute =
  AuthenticatedAdminAuditsRouteImport.update({
    id: '/admin/audits',
    path: '/admin/audits',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminChallengesRoute =
  AuthenticatedAdminChallengesRouteImport.update({
    id: '/admin/challenges',
    path: '/admin/challenges',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminCoachAssignmentRoute =
  AuthenticatedAdminCoachAssignmentRouteImport.update({
    id: '/admin/coach-assignment',
    path: '/admin/coach-assignment',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminCoachesRoute =
  AuthenticatedAdminCoachesRouteImport.update({
    id: '/admin/coaches',
    path: '/admin/coaches',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminExpertsRoute =
  AuthenticatedAdminExpertsRouteImport.update({
    id: '/admin/experts',
    path: '/admin/experts',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminReportsRoute =
  AuthenticatedAdminReportsRouteImport.update({
    id: '/admin/reports',
    path: '/admin/reports',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminRolesRoute = AuthenticatedAdminRolesRouteImport.update({
  id: '/admin/roles',
  path: '/admin/roles',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiPublicBootstrapDemoRoute = ApiPublicBootstrapDemoRouteImport.update({
  id: '/api/public/bootstrap-demo',
  path: '/api/public/bootstrap-demo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/assigned-audits': typeof AuthenticatedAssignedAuditsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/my-audits': typeof AuthenticatedMyAuditsRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/admin/audits': typeof AuthenticatedAdminAuditsRoute
  '/admin/challenges': typeof AuthenticatedAdminChallengesRoute
  '/admin/coach-assignment': typeof AuthenticatedAdminCoachAssignmentRoute
  '/admin/coaches': typeof AuthenticatedAdminCoachesRoute
  '/admin/experts': typeof AuthenticatedAdminExpertsRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/api/public/bootstrap-demo': typeof ApiPublicBootstrapDemoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/assigned-audits': typeof AuthenticatedAssignedAuditsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/my-audits': typeof AuthenticatedMyAuditsRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/admin/audits': typeof AuthenticatedAdminAuditsRoute
  '/admin/challenges': typeof AuthenticatedAdminChallengesRoute
  '/admin/coach-assignment': typeof AuthenticatedAdminCoachAssignmentRoute
  '/admin/coaches': typeof AuthenticatedAdminCoachesRoute
  '/admin/experts': typeof AuthenticatedAdminExpertsRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/api/public/bootstrap-demo': typeof ApiPublicBootstrapDemoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/assigned-audits': typeof AuthenticatedAssignedAuditsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/my-audits': typeof AuthenticatedMyAuditsRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/admin/audits': typeof AuthenticatedAdminAuditsRoute
  '/_authenticated/admin/challenges': typeof AuthenticatedAdminChallengesRoute
  '/_authenticated/admin/coach-assignment': typeof AuthenticatedAdminCoachAssignmentRoute
  '/_authenticated/admin/coaches': typeof AuthenticatedAdminCoachesRoute
  '/_authenticated/admin/experts': typeof AuthenticatedAdminExpertsRoute
  '/_authenticated/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/_authenticated/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/api/public/bootstrap-demo': typeof ApiPublicBootstrapDemoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/assigned-audits'
    | '/dashboard'
    | '/my-audits'
    | '/notifications'
    | '/profile'
    | '/admin/audits'
    | '/admin/challenges'
    | '/admin/coach-assignment'
    | '/admin/coaches'
    | '/admin/experts'
    | '/admin/reports'
    | '/admin/roles'
    | '/admin/users'
    | '/api/public/bootstrap-demo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/assigned-audits'
    | '/dashboard'
    | '/my-audits'
    | '/notifications'
    | '/profile'
    | '/admin/audits'
    | '/admin/challenges'
    | '/admin/coach-assignment'
    | '/admin/coaches'
    | '/admin/experts'
    | '/admin/reports'
    | '/admin/roles'
    | '/admin/users'
    | '/api/public/bootstrap-demo'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/_authenticated/assigned-audits'
    | '/_authenticated/dashboard'
    | '/_authenticated/my-audits'
    | '/_authenticated/notifications'
    | '/_authenticated/profile'
    | '/_authenticated/admin/audits'
    | '/_authenticated/admin/challenges'
    | '/_authenticated/admin/coach-assignment'
    | '/_authenticated/admin/coaches'
    | '/_authenticated/admin/experts'
    | '/_authenticated/admin/reports'
    | '/_authenticated/admin/roles'
    | '/_authenticated/admin/users'
    | '/api/public/bootstrap-demo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiPublicBootstrapDemoRoute: typeof ApiPublicBootstrapDemoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/assigned-audits': {
      id: '/_authenticated/assigned-audits'
      path: '/assigned-audits'
      fullPath: '/assigned-audits'
      preLoaderRoute: typeof AuthenticatedAssignedAuditsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/my-audits': {
      id: '/_authenticated/my-audits'
      path: '/my-audits'
      fullPath: '/my-audits'
      preLoaderRoute: typeof AuthenticatedMyAuditsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/audits': {
      id: '/_authenticated/admin/audits'
      path: '/admin/audits'
      fullPath: '/admin/audits'
      preLoaderRoute: typeof AuthenticatedAdminAuditsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/challenges': {
      id: '/_authenticated/admin/challenges'
      path: '/admin/challenges'
      fullPath: '/admin/challenges'
      preLoaderRoute: typeof AuthenticatedAdminChallengesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/coach-assignment': {
      id: '/_authenticated/admin/coach-assignment'
      path: '/admin/coach-assignment'
      fullPath: '/admin/coach-assignment'
      preLoaderRoute: typeof AuthenticatedAdminCoachAssignmentRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/coaches': {
      id: '/_authenticated/admin/coaches'
      path: '/admin/coaches'
      fullPath: '/admin/coaches'
      preLoaderRoute: typeof AuthenticatedAdminCoachesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/experts': {
      id: '/_authenticated/admin/experts'
      path: '/admin/experts'
      fullPath: '/admin/experts'
      preLoaderRoute: typeof AuthenticatedAdminExpertsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/reports': {
      id: '/_authenticated/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AuthenticatedAdminReportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/roles': {
      id: '/_authenticated/admin/roles'
      path: '/admin/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AuthenticatedAdminRolesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/bootstrap-demo': {
      id: '/api/public/bootstrap-demo'
      path: '/api/public/bootstrap-demo'
      fullPath: '/api/public/bootstrap-demo'
      preLoaderRoute: typeof ApiPublicBootstrapDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAssignedAuditsRoute: typeof AuthenticatedAssignedAuditsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedMyAuditsRoute: typeof AuthenticatedMyAuditsRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedAdminAuditsRoute: typeof AuthenticatedAdminAuditsRoute
  AuthenticatedAdminChallengesRoute: typeof AuthenticatedAdminChallengesRoute
  AuthenticatedAdminCoachAssignmentRoute: typeof AuthenticatedAdminCoachAssignmentRoute
  AuthenticatedAdminCoachesRoute: typeof AuthenticatedAdminCoachesRoute
  AuthenticatedAdminExpertsRoute: typeof AuthenticatedAdminExpertsRoute
  AuthenticatedAdminReportsRoute: typeof AuthenticatedAdminReportsRoute
  AuthenticatedAdminRolesRoute: typeof AuthenticatedAdminRolesRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAssignedAuditsRoute: AuthenticatedAssignedAuditsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedMyAuditsRoute: AuthenticatedMyAuditsRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedAdminAuditsRoute: AuthenticatedAdminAuditsRoute,
  AuthenticatedAdminChallengesRoute: AuthenticatedAdminChallengesRoute,
  AuthenticatedAdminCoachAssignmentRoute:
    AuthenticatedAdminCoachAssignmentRoute,
  AuthenticatedAdminCoachesRoute: AuthenticatedAdminCoachesRoute,
  AuthenticatedAdminExpertsRoute: AuthenticatedAdminExpertsRoute,
  AuthenticatedAdminReportsRoute: AuthenticatedAdminReportsRoute,
  AuthenticatedAdminRolesRoute: AuthenticatedAdminRolesRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiPublicBootstrapDemoRoute: ApiPublicBootstrapDemoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
